### ISSUE TITLE
Missing .umd files in subsequent releases after 1.0.0

### ISSUE THREAD

**Issue by Raruto** [tmcw/togeojson#13]
Hi Tom,
I believe that the latest current version ([0.0.3](https://unpkg.com/@tmcw/togeojson@3.0.0)) actually present on unpkg lacks of some files (or there are some problems with your [package.json](https://github.com/tmcw/togeojson/blob/v3.0.0/package.json) configuration).

In particular, I noticed that because i was trying to import it with browserify, but:

```js
var toGeoJSON = require("./node_modules/@tmcw/togeojson/dist/togeojson.js"); // OK: pointing directly to installed file

var toGeoJSON = require("@tmcw/togeojson"); // Throws cannot find module '@tmcw/togeojson'
```

_Have a nice day,
Raruto_

**Comment by tmcw** [comment]
Thanks for the note - I've fixed the typo in 3.0.1.
