### ISSUE TITLE
Cannot convert KML file with Document tag to GeoJSON

### ISSUE THREAD

**Issue by digoburigo** [tmcw/togeojson#14]
[city.kml.zip](https://github.com/tmcw/togeojson/files/3438513/city.kml.zip)
This kml file has the feature inside the document and folder tags and the conversion does not work. How can i be able to make the conversion?
```
<Document>
<Folder>
...
</Folder>
</Document>
```
Conversion error with the tags
![image](https://user-images.githubusercontent.com/28462822/61998751-39e89f80-b08b-11e9-8962-87f8ad4b14b3.png)

Conversion without the tags works but without the styles
![image](https://user-images.githubusercontent.com/28462822/61998764-73b9a600-b08b-11e9-8654-f8aa98d6fa66.png)

**Comment by tmcw** [comment]
Your example isn't a valid XML file: if you [try to validate it](https://www.xmlvalidation.com/index.php?id=1&L=0), the `xsi:schemaLocation` attribute on the `Document` element will stop the validator. If you remove that attribute, conversion will work.

**Comment by digoburigo** [comment]
Thanks, that was the problem
