### ISSUE TITLE
Can't convert NOAA KML

### ISSUE THREAD

**Issue by jlubeck** [tmcw/togeojson#15]
I'm trying to convert this file: https://www.nhc.noaa.gov/gis/kml/nhc_active.kml

But the conversion is just returning this Object:

`Object {type: "FeatureCollection", features: Array(0)}`

Any idea what is wrong and if it can be fixed?

Thanks!

**Comment by tmcw** [comment]
The issue is NetworkLinks - see the note in the readme about that limitation. https://github.com/tmcw/togeojson#why-doesnt-togeojson-support-networklinks

**Comment by jlubeck** [comment]
Can't the network link be converted to a regular string (or something) and give us the option to then do the download and re-conversion manually? (without having the library have to handle this).

Wouldn't that be better than to just return an empty object?

Thanks for the ultra quick reply!

**Comment by tmcw** [comment]
There's no equivalent representation for a network link in GeoJSON, and I'd rather not invent one. If you'd like to extract the links, it's as easy as `getElementsByTagName('NetworkLink')` once you have an XML DOM.

**Comment by jlubeck** [comment]
Ok, thank you
