### ISSUE TITLE
browserify error

### ISSUE THREAD

**Issue by hoogw** [tmcw/togeojson#27]
I try to browserify , but run into error, 

                `browserify index.js --s togeojson -o dist/togeojson.js

                  /Users/nicole/node/togeojson/index.js:1
                   export { gpx, gpxGen } from "./lib/gpx";
                  ^
                  ParseError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by tmcw** [comment]
It looks like, in this context, you're in a clone of this repository (togeojson/index.js), and trying to get browserify to create a standalone bundle of togeojson?

Assuming that's the case, first off: you can get a standalone bundle, if you're in a git checkout, by running:

```
$ npm install
$ npm run prepare
```

There are also prebuilt standalone bundles on unpkg: https://unpkg.com/browse/@tmcw/togeojson@4.0.0/dist/ (you'd want the .umd ones, most likely).

**Comment by hoogw** [comment]
I have tried you suggestion, but still get error as:

        `Uncaught (in promise) ReferenceError: kml is not defined
    at convert_kml_to_geojson (helper.js:313)`

html, script tag is: 

`<script src='https://unpkg.com/browse/@tmcw/togeojson@4.0.0/dist/togeojson.umd.js'> `


js call this function              
                         `

              function convert_kml_to_geojson(kml_string){

                var kml_dom = new DOMParser().parseFromString(kml_string, "text/xml");
                console.log( 'kml_dom ', kml_dom );
            
            
            
               console.log( kml );
               console.log( kml(kml_dom) );
               
            
            
            
               }`

**Comment by tmcw** [comment]
You'll need to refer to the `kml` function of toGeoJSON as `toGeoJSON.kml`, instead of just `kml`.

**Comment by hoogw** [comment]
This time I get 
            `Uncaught (in promise) ReferenceError: toGeoJSON is not defined
    at convert_kml_to_geojson (helper.js:313)`

              ` function convert_kml_to_geojson(kml_string){

                var kml_dom = new DOMParser().parseFromString(kml_string, "text/xml");
                console.log( 'kml_dom ', kml_dom );
            
            
            
               console.log( 'kml reference ->' ,toGeoJSON.kml );
               console.log( 'kml -> geojson -> ', toGeoJSON.kml(kml_dom) );
               
            
            
            
               }`

**Comment by hoogw** [comment]
I have tried, both script tag, with/without type='module'
same error 
                                `toGeoJSON is not defined`

           `<script type='module' src='https://unpkg.com/browse/@tmcw/togeojson@4.0.0/dist/togeojson.umd.js'> `

**Comment by hoogw** [comment]
I found the reason: 
      my browser console complain when load "togeojson.umd.js"

                     `Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by hoogw** [comment]
I use opera, seem like failed to load module at the first place, because of  strict......

**Comment by hoogw** [comment]
I tried with firefox, get more info
           `Loading module from “https://unpkg.com/browse/@tmcw/togeojson@4.0.0/dist/togeojson.umd.js” was blocked because of a disallowed MIME type (“text/html”).`

learn more at: 

[https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Content-Type-Options?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default](https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Content-Type-Options?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)

**Comment by hoogw** [comment]
I tried with google chrome, get this, is ES6 module problem,many people get this.

      `Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by tmcw** [comment]
The URL should be https://unpkg.com/@tmcw/togeojson@4.0.0/dist/togeojson.umd.js

**Comment by hoogw** [comment]
Ok, I found a fix !!!!!!!
Simply saying:

                      You need to save  togeojson.umd.js file on to your node http server! or Python http server!!!
                          if you use the online "unpkg.com" version, your browser will block load module due to unpkg.com server incorrectly respond MIME type!!!
                          if you put that file on apache2.4 server, likely failed for same reason(not test yet)

Why?  because only node http server and python http server can correctly respond MIME type
see this top accepted answer:
      [https://stackoverflow.com/questions/46138375/trouble-with-es6-modules#](https://stackoverflow.com/questions/46138375/trouble-with-es6-modules#)
 
                               The problem is NOT caused by toGeoJSON module iteself, it caused by how you get this module from( unpkg.com, apache will failed, node and python http server will success)

**Comment by hoogw** [comment]
Now I save togeojson.umd.js to my node.js server, no more error. 
works like a charming!!! after 4 hours painful countless try and failure.



I will continue to try save it on apache2.4 server, see what happen.

On other side, do you have any idea to work around it?

**Comment by tmcw** [comment]
The solution is what I posted before: use

```
<script src='https://unpkg.com/@tmcw/togeojson@4.0.0/dist/togeojson.umd.js'></script>
```

**Comment by hoogw** [comment]
yes, this one works:
             `https://unpkg.com/@tmcw/togeojson@4.0.0/dist/togeojson.umd.js`
but this one DO NOT work:
              `https://unpkg.com/browse/@tmcw/togeojson@4.0.0/dist/togeojson.umd.js`

I believe the local dist, by npm install is the same as first one (works) above.
So, for safe, just run a local npm install, get it from dist folder.
