### ISSUE TITLE
response.xml is not a function error

### ISSUE THREAD

**Issue by hoogw** [tmcw/togeojson#28]
I run into 

              `response.xml is not a function error`
           
I fix it by use response.responseXML, then it works, 

       `<script type="module">
            import { kml } from "https://unpkg.com/@tmcw/togeojson?module";
  
    fetch("https://opendata.arcgis.com/datasets/30400d96c9ef427380ff05dabd09fa2e_26.kml")
      .then(function(response) {
        return response.responseXML;
      })
      .then(function(xml) {
        console.log(kml(xml));
      });
  </script>`

Further, I run into other error:

                      `togeojson.es.js?module:541 Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagName' of undefined
    at kmlGen (togeojson.es.js?module:541)
    at kmlGen.next (<anonymous>)
    at Function.from (<anonymous>)
    at kml (togeojson.es.js?module:577)
    at kml_to_geojson.html:9`

**Comment by hoogw** [comment]
Now I save js file to apache2.4 server,

             `
                 <script src='../share/lib/togeojson/dist/togeojson.umd.js'></script>

                   <script>
    
  
    fetch("https://opendata.arcgis.com/datasets/30400d96c9ef427380ff05dabd09fa2e_26.kml")
      .then(function(response) {
        return response.responseXML;
      })
      .then(function(xml) {


               // console.log(kml(xml));

               //console.log( 'kml reference ->' ,toGeoJSON.kml );
               console.log( 'kml -> geojson -> ', toGeoJSON.kml(xml) );
               
            



                     });
                  </script>`

I still get error: 
                            `uncaught (in promise) TypeError: Cannot read property 'getElementsByTagName' of undefined
    at S (kml.js:273)
    at S.next (<anonymous>)
    at Function.from (<anonymous>)
    at Object.e.kml (kml.js:309)
    at kml_to_geojson.html:43`

**Comment by tmcw** [comment]
I've corrected that readme example.

```js
  fetch("test/data/linestring.kml")
    .then(function(response) {
      return response.text();
    })
    .then(function(xml) {
      console.log(kml(new DOMParser().parseFromString(xml, "text/xml")));
    });
```

**Comment by hoogw** [comment]
I get another error:

This one is on apache2.4 sever, get error,

But I have same one run on node.js, I do not get any error. kml, scipt url all same

                   `Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagName' of undefined
    at S (kml.js:273)
    at S.next (<anonymous>)
    at Function.from (<anonymous>)
    at Object.e.kml (kml.js:309)
    at kml_to_geojson.html:46`




                 `<script src='https://unpkg.com/@tmcw/togeojson@4.0.0/dist/togeojson.umd.js'>    
                   </script>
 
         <script>
    
  
    fetch("https://opendata.arcgis.com/datasets/30400d96c9ef427380ff05dabd09fa2e_26.kml")
      .then(function(response) {
        return response.responseXML;
      })
      .then(function(xml) {


               // console.log(kml(xml));

               //console.log( 'kml reference ->' ,toGeoJSON.kml );
               console.log( 'kml -> geojson -> ', toGeoJSON.kml(xml) );
               
            



             });
           </script>`
