### ISSUE TITLE
Move `properties.coordTimes` to `properties.coordinateProperties.times`

### ISSUE THREAD

**Issue by jsejcksn** [tmcw/togeojson#29]
Hi Tom:

I have just started to really explore the GPX format, so forgive any ignorance on my part.

In doing some research about GeoJSON ↔️ GPX conversion and parsers, it seems like there's not a standardized extension for trackpoint metadata, so you invented the `[feature].properties.coordTimes` array when you originally wrote this lib for Mapbox. (If any of that's not right, please correct me.)

It looks like there has been discussion about using `[feature].properties.coordinateProperties` to namespace data associated to coordinates, and that `coordTimes` maps to `coordinateProperties.times`.

Most of the discussion I found seems to never converge on consensus. The namespacing makes sense to me. Will you share your current perspective on this, and maybe point me to more information if I missed something official?

**Comment by tmcw** [comment]
That is the case. There's nothing more official than a repository, because there's neither the means nor the need to get an official stamp (OGC does standards, but mostly for the military, and they make mostly bad standards, IETF makes good standards but it takes months & a corporate sponsor). If anyone were to carry the defacto spec forward, it would be an entity like Strava or Mapbox, but it's really up to them.

Both coordTimes and coordProperties _work_ as representations, and are probably the right way to represent that kind of data. We've had some threads about them, and no better alternative floated to the surface. toGeoJSON uses coordTimes mostly just because of legacy and because it'll be a major version bump to switch to coordProperties and nobody's asked or proposed a PR - though I wouldn't be opposed to one.

**Comment by jsejcksn** [comment]
Thanks. In that case, I'd like to convert this to a request for that change.

To reiterate the specific request: I'm asking to move the current property `[feature].properties.coordTimes` to `[feature].properties.coordinateProperties.times`, per [the extension draft by Mapbox](https://github.com/mapbox/geojson-coordinate-properties). It has been adopted by at least [one other product](https://www.mapillary.com/developer/api-documentation/#:~:text=coordinateProperties%20is%20an%20extension%20to%20GeoJSON).

I think this change will also allow for more structure in supporting [additional waypoint properties](https://www.topografix.com/GPX/1/1/#type_wptType) beyond `times` for each set of coordinates. For example: `names`, `descriptions`, `types`, `heart`, etc.

(To be clear, I'm not recommending those specific strings as keys for the additional waypoint properties, rather I'm just illustrating the idea.)

**Comment by tmcw** [comment]
Okay! I'll add this to my list for when I have time & focus, otherwise happy to accept a PR that implements this feature.

**Comment by RalucaNicola** [comment]
I could make a PR for this... but I'm not sure how this should work: would the `heartRate` also move to `coordinateProperties` or just the `times` property? to be honest I'm not sure what the advantage is, if only `times` moves there.

**Comment by tmcw** [comment]
Yep, the idea is that `heartRates` would move to `coordinateProperties.heart`, and `times` would move to `coordinateProperties.times`.

The current representation and the geojson-coordinate-properties representation are equivalent in power and roughly the same in terms of efficiency/size/etc. The only advantage is that geojson-coordinate-properties is more precisely explained by a spec and there may be other implementations that adopt the geojson-coordinate-properties style.

**Comment by RalucaNicola** [comment]
sounds good, I'll have a look next weekend to see if I can make a PR :)

**Comment by RalucaNicola** [comment]
we moved the `heartRates` and `times` to `coordinateProperties` @jsejcksn. We can probably close this?

**Comment by jsejcksn** [comment]
Hi @RalucaNicola

Thanks for creating the PR that was merged. I am wondering about its conformance to the proposed extension I linked to in the original message. In the proposal, [it states](https://github.com/mapbox/geojson-coordinate-properties#heart):

> Members of the `coordinateProperties` property can have any name, but semantics of two names are defined:
>   - `times`
>     ...
>   - `heart`
>     ...

In your PR, you implemented `heart` as `heartRate`. Was there a reason that you used that name instead of the one defined in the extension proposal?

**Comment by RalucaNicola** [comment]
oh, not sure how I came up with `heartRates` tbh 🙈 
I'll change it to `heart` if Tom agrees :)

**Comment by jsejcksn** [comment]
> oh, not sure how I came up with `heartRates` tbh 🙈
> I'll change it to `heart` if Tom agrees :)

No worries. 😄 
@tmcw Thoughts?

**Comment by tmcw** [comment]
Yep, whoops - should've caught that. Let's change it.

**Comment by RalucaNicola** [comment]
I'll make a PR next week.

**Comment by jsejcksn** [comment]
Thanks @RalucaNicola
