### ISSUE TITLE
Typescript import results in undefined

### ISSUE THREAD

**Issue by ajmas** [tmcw/togeojson#34]
I am using a the packages in a nodejs Typescript based project, where I launch the code using `ts-node`, but I am getting an `undefined` when I used the import:

```ts
import toGeoJson from '@tmcw/togeojson';
```

Looking at the source of 4.1.0 suggests I should be using named imports, per https://github.com/tmcw/togeojson/blob/master/index.js

Does this mean the docs are out of date or there is a missing default export?

Note this code does work:

```ts
import { kml } from '@tmcw/togeojson';

const data = fs.readFileSync(inputFile, 'utf8')
const kmlData = new DOMParser().parseFromString(data);
```

**Comment by tmcw** [comment]
I don't think that there is any documentation that suggests that there's a default ES Module export: the documentation demonstrates usage with require() and usage with a named import and ES modules. I could add another example to make this clearer, but afaict there's no suggestion that `import toGeoJSON from …` would work.

**Comment by ajmas** [comment]
In the NodeJS example:

```
const tj = require("@tmcw/togeojson");
```

which as ES6/TS would be:

```
import tj from '@tmcw/togeojson';
```

This would suggest in ES6 in source:

```
export default ...
```

**Comment by tmcw** [comment]
Hi, yep - ES modules don't translate to CommonJS like that, for a number of reasons (see [some unpacking in this gist](https://gist.github.com/tmcw/b90666454d424ebdaa3904dc1d9c7620)).

The closest equivalent of

```js
const a = require('mod');
```

In ES modules is

```
import * as a from "mod";
```

Which works in toGeoJSON.
