### ISSUE TITLE
TCX support

### ISSUE THREAD

**Issue by evanbarter** [tmcw/togeojson#35]
Hi Tom, thanks for your ongoing support of this project.

Any chance you'd consider walking back [this decision](https://github.com/mapbox/togeojson/issues/86)?

I've got a fork of tcx with a couple of small QoL fixes.

Thanks!

**Comment by tmcw** [comment]
Sure, that sounds like a decent idea! Let's re-add tcx.

**Comment by evanbarter** [comment]
Great! I'll try and land a PR this week.

**Comment by tmcw** [comment]
Released in 4.2.0! Thanks for starting that effort.
