### ISSUE TITLE
For tcx files `HeartRateBpm` doesn't show up in the geojson feature properties

### ISSUE THREAD

**Issue by RalucaNicola** [tmcw/togeojson#41]
Parsing a tcx file I noticed that `heartRates` coordinate property are not added to the final geojson feature properties.

Repro: 

1. Open up this glitch example: https://glitch.com/edit/#!/defiant-unleashed-ghoul
1. Click Show -> Next to code
1. Open up the console and inspect the feature in geojson -> it has a `coordTimes`, but not `heartRates`.
1. Notice that the original dataset has HeartRateBpm: https://github.com/RalucaNicola/togeojson/blob/raluca/heartRateTcx/test/data/tour_hr.tcx

**Comment by tmcw** [comment]
Fixed in #42!
