### ISSUE TITLE
Namespace prefix xsi for schemaLocation on Document is not defined

### ISSUE THREAD

**Issue by furick1** [tmcw/togeojson#45]
[CrossWGS.kml.txt](https://github.com/tmcw/togeojson/files/5880507/CrossWGS.kml.txt)
Attached file errors on upload at https://observablehq.com/@tmcw/convert-kml-to-geojson and gives error of "geojson = Error: This page contains the following errors:error on line 3 at column 211: Namespace prefix xsi for schemaLocation on Document is not defined
Below is a rendering of the page up to the first error."

Is this a bug or invalid kml or something else?

**Comment by tmcw** [comment]
That error's happening before togeojson's code runs, in the part of that notebook that's simply parsing XML. That's an invalid XML file - you can confirm this with an online validator, like https://www.xmlvalidation.com/

You can fix that issue in the file by changing the document tag from

```xml
<Document id="CrossWGS" xsi:schemaLocation="http://www.opengis.net/kml/2.2 http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd http://www.google.com/kml/ext/2.2 http://code.google.com/apis/kml/schema/kml22gx.xsd">
```

to

```xml
<Document id="CrossWGS">
```

The program exporting this data likely has a bug.
