### ISSUE TITLE
Eliminate the need for xml2str

### ISSUE THREAD

**Issue by tmcw** [tmcw/togeojson#5]
This is a gross method that's a sticking point for our node / browser compatibility. For hashing styles, we don't need a full-fledged serialization step. Possibly I can use [isEqualNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/isEqualNode) instead, or manually serialize only a subset.

**Comment by clintharris** [comment]
So to summarize some of your comments from #8, some goals for a PR addressing this ticket (I think) are:
  * Maintain support for hashing (i.e., the output GeoJSON  features should continue to have `properties.styleHash` and `properties.styleMapHash` values).
  * Stop relying on any implementation of `XMLSerializer`; come up with some lightweight method of converting `<Style>` chunks to strings instead.

Do you still see `isEqualNode()` being used in some way if hashing is maintained?

**Comment by clintharris** [comment]
Regarding serializing the XML, [xmlserializer](https://github.com/cburgmer/xmlserializer/blob/master/xmlserializer.js) ([npm](https://www.npmjs.com/package/xmlserializer)) looks pretty lightweight.

Any objections to a PR that incorporates this or is your preference to have a more minimal solution and no dependencies?

In other words, maybe you were thinking that, instead of hashing a *literal* string version of the XML, a DIY solution just hashes a concatenation of the bare minimum amount of substrings from `<Style>` and `<StyleMap>` nodes to do equality checks?

For example,
```xml
  <Style id="a">
    <IconStyle>
      <color>a1ff00ff</color>
      <scale>1.3</scale>
      <Icon>
        <href>http://myserver.com/icon.jpg</href>
      </Icon>
    </IconStyle>
  </Style>
```
could be converted to something like a concatenation of tags/attributes/values (as long as its deterministic) like: `"Style#id=4.IconStyle.color.a1ff00ff.scale.1.3.Icon.href.http://myserver.com/icon.jpg"` and then hashed?

**Comment by tmcw** [comment]
I think `isEqualNode()` isn't the solution I had hoped for, because I can't imagine a way to use it efficiently; if you have many unique styles, for every additional style, you’d need to compare it to every previous style for equality.

xmlserializer is a decent starting point but I think it's still overkill for togeojson, and I wouldn't want to add a dependency. Distilling xmlserializer by hand for a bit leads me to:

```js
function serialize(node) {
  if (node.tagName) {
    var output = "<" + node.tagName;
    var attrs = node.attributes || node.attrs;

    for (var i = 0; i < attrs.length; i++) {
      output += " " + attrs[i].name + '="' + attrs[i].value + '"';
    }

    if (node.childNodes.length > 0) {
      output += ">";
      for (var i = 0; i < node.childNodes.length; i++) {
        output += serialize(node.childNodes[i]);
      }
      output += "</" + node.tagName + ">";
    } else {
      output += "/>";
    }
    return output.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g, "");
  } else if (node.nodeName === "#text") {
    return node.nodeValue || node.value || "";
  } else if (node.nodeName === "#cdata-section") {
    return "<![CDATA[" + node.nodeValue + "]]>";
  }
  return "";
};
```

Which I think is capable of handling all the necessary cases for style hashing.

**Comment by tmcw** [comment]
I think this version, a bit shorter and using let/const/of would also work because we don't really need the output to be XML, just to be different for different XML values.

```js
function serialize(node) {
  if (node.tagName) {
    let output = node.tagName;
    let attrs = node.attributes || node.attrs;
    for (let attr of attrs) output += attr.name + attr.value;
    for (let node of childNodes) output += serialize(node);
    return output;
  }
  if (node.nodeName === "#text") {
    return node.nodeValue || node.value || "";
  }
  if (node.nodeName === "#cdata-section") {
    return node.nodeValue;
  }
  return "";
};
```

**Comment by tmcw** [comment]
This work intersects with a refactor I'm working on, so heads-up that I'll probably open a PR with this change soon.

**Comment by tmcw** [comment]
Fixed in v2

**Comment by clintharris** [comment]
Thanks for the quick fix (and the slick, new `yield` feature)!
