### ISSUE TITLE
Ability to run in web worker context

### ISSUE THREAD

**Issue by clintharris** [tmcw/togeojson#8]
`kmlToGeoJson()` currently depends on an implementation of `XMLSerializer` (i.e., by way of `xml2str()`), but the current set of environment checks in `kml.js` which try to pick an implementation (e.g., dynamically requiring [xmldom](https://github.com/jindw/xmldom) in Node environments) doesn't work in a web worker context. (Context: web workers don't have access to `window.XMLSerializer`.)

Before working on a PR, would be great to get some guidance from @tmcw on preferred solutions. Some ideas:

1. Modify `kmlToGeoJson()` to accept a new arg that optionally overrides `xml2str()`. Example:
```javascript
kmlToGeoJson(doc, serializeXml=xml2str) {
  // ...
  for (let k = 0; k < styles.length; k++) {
    const hash = okhash(serializeToString(styles[k])).toString(16); // 👈👈👈 
    styleIndex["#" + styles[k].getAttribute("id")] = hash;
    styleByHash[hash] = styles[k];
  }
  // ...
}
```

2. Try to **dynamically** import XMLSerializer from xmldom in a web worker context (similar to how `require()` is used in a Node env). This might be tricky since dynamic imports via `import()` are async and everything in `kml.js` is currently synchronous.

3. Stop serializing/hashing XML (i.e., get rid of `xml2str()`, per #5). Possible drawback here is that the produced GeoJSON features would no longer have `properties.styleHash` and `properties.styleMapHash`--so not exactly a backwards-compatible change.

Thoughts?

**Comment by tmcw** [comment]
I think 3 is the solution all these flow to - the first lets you override xml2str but leaves open what it'd be, the second would require two files to use togeojson and also makes it unclear what you'd be importing (xmldom? shipping that to a browser would be pretty rough), whereas the third gives us consistent behavior and no holes to fall down. I think it would be possible to implement (3) without dropping styleHash and styleMapHash - given that we can ignore comments etc and we can probably encode a good-enough subset of XML structure, implementing xml2str without using XMLSerializer seems feasible.

**Comment by clintharris** [comment]
Gotcha--so seems like #5 is probably going to address this.
